# Generated by Django 4.2.5 on 2023-09-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counsellors', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('students_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=200)),
                ('phoneNo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=500)),
                ('counsellor_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='counsellors.counsellors')),
                ('courses_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
    ]
