# Generated by Django 4.2.5 on 2023-11-13 15:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_courseunits_id_alter_courseunits_course_id'),
        ('students', '0007_alter_enrolledcourses_coursephoto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledcourses',
            name='completion_status',
        ),
        migrations.RemoveField(
            model_name='enrolledcourses',
            name='counsellor_id',
        ),
        migrations.RemoveField(
            model_name='enrolledcourses',
            name='coursePhoto',
        ),
        migrations.AlterField(
            model_name='enrolledcourses',
            name='courses_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='enrolledcourses',
            name='enrolled_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
