# Generated by Django 4.2.5 on 2023-11-13 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0010_rename_courses_id_enrolledcourses_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='students_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
