# Generated by Django 4.2.5 on 2023-11-26 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_courseunits_id_alter_courseunits_course_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0011_alter_students_students_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourses',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='enrolledcourses',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
