# Generated by Django 4.2.5 on 2023-11-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counsellors',
            old_name='counsellors_id',
            new_name='counsellor_id',
        ),
        migrations.RemoveField(
            model_name='counsellors',
            name='password',
        ),
        migrations.AddField(
            model_name='counsellors',
            name='gender',
            field=models.CharField(choices=[('1', 'MALE'), ('2', 'FEMALE'), ('3', 'Any other')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='counsellors',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='counsellors',
            name='phoneNo',
            field=models.CharField(max_length=100),
        ),
    ]
