# Generated by Django 4.2.5 on 2023-11-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellors', '0009_alter_counsellors_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellors',
            name='profile_picture',
            field=models.ImageField(blank=True, default='Counsellorsphotos/2023/11/16/best_company_law_teacher_in_India_7Be6cfJ.jpg', upload_to='Counsellorsphotos/%Y/%m/%d/'),
        ),
    ]
