# Generated by Django 4.2.5 on 2023-09-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counsellors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('courses_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=20)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='counsellors.counsellors')),
            ],
        ),
    ]
