# Generated by Django 4.2.5 on 2023-11-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_counsellor_courses_counsellor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit1', models.FileField(upload_to='pdf')),
                ('unit2', models.FileField(upload_to='pdf')),
                ('unit3', models.FileField(upload_to='pdf')),
                ('unit4', models.FileField(upload_to='pdf')),
                ('unit5', models.FileField(upload_to='pdf')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
    ]
