# Generated by Django 4.2.5 on 2023-11-13 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseunits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseunits',
            name='id',
        ),
        migrations.AlterField(
            model_name='courseunits',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses.courses'),
        ),
    ]
