# Generated by Django 4.2.5 on 2023-11-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellors', '0002_rename_counsellors_id_counsellors_counsellor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellors',
            name='username',
        ),
    ]
