# Generated by Django 4.2.5 on 2023-11-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellors', '0003_remove_counsellors_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellors',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='Counsellorsphotos/%Y/%m/%d/'),
        ),
    ]
