# Generated by Django 4.2.5 on 2023-11-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellors', '0005_alter_counsellors_counsellor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellors',
            name='username',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
