# Generated by Django 4.2.5 on 2023-11-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrolledcourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_id', models.IntegerField()),
                ('courses_id', models.IntegerField()),
                ('counsellor_id', models.IntegerField()),
                ('completion_status', models.IntegerField(default=0)),
                ('enrolled_date', models.DateTimeField()),
                ('courses_name', models.CharField(max_length=20)),
                ('course_duration', models.TimeField()),
                ('coursePhoto', models.ImageField(upload_to='')),
            ],
        ),
    ]
