# Generated by Django 4.2.5 on 2023-11-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_students_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('1', 'MALE'), ('2', 'FEMALE'), ('3', 'Any other')], default='1', max_length=20),
        ),
    ]
