# Generated by Django 4.2.5 on 2023-11-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_students_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourses',
            name='students_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
    ]
