# Generated by Django 4.2.5 on 2023-11-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_enrolledcourses_completion_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledcourses',
            name='course_duration',
        ),
        migrations.RemoveField(
            model_name='enrolledcourses',
            name='courses_name',
        ),
    ]
