# Generated by Django 4.2.5 on 2023-11-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_enrolledcourses_course_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledcourses',
            old_name='courses_id',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='enrolledcourses',
            old_name='students_id',
            new_name='student_id',
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='Studentsphotos/%Y/%m/%d/'),
        ),
    ]
